Repository team-MiniJin/FE, pull requests merged in 2024-06, with the labels that each got.

#10 PR: Add My Plans UI with carousel and Infinite scroll
  package-lock.json
  package.json
  src/app/api/plans/consts/api.ts
  src/app/api/plans/route.ts
  src/app/api/plans/upcoming/route.ts
  src/app/creating-plan/page.tsx
  src/app/exploring/page.tsx
  src/app/layout.tsx
  src/app/my-travels/page.tsx
  src/app/travel-info/page.tsx
  src/components/ui/button.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/features/index.tsx
  src/features/plan/ui/CreatingPlanButton.tsx
  src/shared/hooks/useInfiniteScroll.ts
  src/shared/index.tsx
  src/shared/utils/calculateStayDuration.ts
  src/widgets/creatingPlan/schema/schema.ts
  src/widgets/creatingPlan/ui/CreatingPlan.tsx
  src/widgets/creatingPlan/ui/Form.tsx
  src/widgets/header/consts/gnb.ts
  src/widgets/header/ui/GNB.tsx
  src/widgets/index.tsx
  src/widgets/myPlans/api/fetchMyPlans.ts
  src/widgets/myPlans/model/useMyPlans.ts
  src/widgets/myPlans/types/myPlans.ts
  src/widgets/myPlans/ui/MyPlan.tsx
  src/widgets/myPlans/ui/MyPlans.tsx
  src/widgets/upcomingPlans/api/fetchUpcomingPlans.ts
  src/widgets/upcomingPlans/model/useUpcomingPlans.ts
  src/widgets/upcomingPlans/types/upcomingplan.ts
  src/widgets/upcomingPlans/ui/UpcomingPlan.tsx
  src/widgets/upcomingPlans/ui/UpcomingPlans.tsx
Labels: enhancement

#15 ✨ feat: 회원가입 페이지 기능 구현
  .gitmessage.txt
  src/app/globals.css
  src/shared/index.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/Input.tsx
  src/shared/utils/submitForm.ts
  src/shared/utils/validateField.ts
  src/widgets/join/ui/JoinForm.tsx
  src/widgets/join/utils/validators.ts
Labels: enhancement

#18 [✨feat] Kakao Map API를 이용한 지도 추가 및 경로에 대한 폴리라인 표시
  package-lock.json
  src/shared/constants/api.ts
  src/shared/utils/fetcher.ts
  src/widgets/my-plan-list/types/myPlans.ts
  src/widgets/my-plan-list/ui/MyPlan.tsx
  src/widgets/my-plan-list/ui/MyPlans.tsx
  src/widgets/my-plan-list/util/getCoordinates.ts
  src/widgets/plan-simple-view/ui/PlanSimpleView.tsx
  src/widgets/plan-simple-view/ui/ViewDetailButton.tsx
  src/widgets/polyline-map/ui/PolylineMap.tsx
Labels: enhancement

#22 [✨feat] 금주 인기 여행 일정 UI 개발
  src/app/ReactQueryProvider.tsx
  src/app/exploring/page.tsx
  src/app/place-info/page.tsx
  src/shared/api/getMyBookmarks.ts
  src/shared/hooks/useCarousel.ts
  src/shared/model/useMyBookmarks.ts
  src/widgets/header/ui/GNB.tsx
  src/widgets/index.tsx
  src/widgets/popular-plans/api/getPopularPlans.ts
  src/widgets/popular-plans/mock/data.ts
  src/widgets/popular-plans/model/usePopularPlans.ts
  src/widgets/popular-plans/types/popular-plan-type.ts
  src/widgets/popular-plans/ui/PopularPlan.tsx
  src/widgets/popular-plans/ui/PopularPlans.tsx
  src/widgets/search-place/model/useSearchPlace.tsx
  src/widgets/search-place/types/address-type.ts
  src/widgets/search-place/types/keyword-type.ts
  src/widgets/search-place/ui/SearchedAddressItem.tsx
  src/widgets/search-place/ui/SearchedKeywordItem.tsx
  src/widgets/upcoming-plans/api/fetchUpcomingPlans.ts
  src/widgets/upcoming-plans/model/useUpcomingPlans.ts
  src/widgets/upcoming-plans/types/upcoming-plan-type.ts
  src/widgets/upcoming-plans/ui/UpcomingPlan.tsx
  src/widgets/upcoming-plans/ui/UpcomingPlans.tsx
Labels: enhancement

#24 ✨ Feat: 여행정보 페이지 구현
  .env
  src/app/layout.tsx
  src/app/travel-info/page.tsx
  src/shared/index.tsx
  src/shared/ui/KakaoMap.tsx
  src/widgets/index.tsx
  src/widgets/travel-info/components/AreaCode.tsx
  src/widgets/travel-info/components/AreaFilter.tsx
  src/widgets/travel-info/components/CategoryFilter.tsx
  src/widgets/travel-info/components/PlacesList.tsx
  src/widgets/travel-info/components/SearchKeyword.tsx
  src/widgets/travel-info/components/SigunguCode.tsx
  src/widgets/travel-info/types/Place.ts
Labels: enhancement

#27 ✨ Feat: 장소선택필터 리셋기능 추가
  .gitignore
  src/app/travel-info/page.tsx
  src/widgets/travel-info/components/AreaFilter.tsx
  src/widgets/travel-info/components/CategoryFilter.tsx
  src/widgets/travel-info/components/PlacesList.tsx
  src/widgets/travel-info/components/SearchKeyword.tsx
  src/widgets/travel-info/hooks/useInfiniteScroll.ts
Labels: documentation

#28 ✨ Feat: 채팅기능 추가
  src/app/find-companion/page.tsx
  src/widgets/chat/mockdata/chatRooms.ts
  src/widgets/chat/mockdata/messages.ts
  src/widgets/chat/mockdata/mockFunctions.ts
  src/widgets/chat/type/chat.ts
  src/widgets/chat/ui/ChatPage.tsx
  src/widgets/chat/ui/ChatRoom.tsx
  src/widgets/chat/ui/Chatting.tsx
  src/widgets/chat/ui/CreateRoom.tsx
  src/widgets/header/constants/gnb.ts
  src/widgets/index.tsx
Labels: enhancement

#30 [💄layout] 나의 여행 일정 페이지 Skeleton UI 적용
  .vscode/settings.json
  src/components/ui/skeleton.tsx
  src/shared/constants/api.ts
  src/shared/constants/style.ts
  src/shared/index.tsx
  src/widgets/my-plan-list/ui/MyPlan.tsx
  src/widgets/my-plan-list/ui/MyPlans.tsx
  src/widgets/upcoming-plans/ui/UpcomingPlan.tsx
  src/widgets/upcoming-plans/ui/UpcomingPlans.tsx
Labels: enhancement

#32 ✨ Feat: 회원가입, 로그인, 로그아웃 기능
  package-lock.json
  src/app/layout.tsx
  src/shared/api/AuthContext.tsx
  src/shared/index.tsx
  src/widgets/header/ui/Header.tsx
  src/widgets/header/ui/LogoutButton.tsx
  src/widgets/header/ui/MyPageLink.tsx
  src/widgets/join/ui/JoinForm.tsx
  src/widgets/login/ui/LogInForm.tsx
Labels: enhancement

#34 ✨ Feat: 카카오로그인 구현
  src/app/kakao-redirect/page.tsx
  src/shared/utils/fetcher.ts
  src/widgets/login/ui/LogInForm.tsx
Labels: documentation, enhancement

#40 ✨ Feat : 회원정보 찾기, 수정, 탈퇴기능 추가
  src/app/delete-account/page.tsx
  src/shared/ui/EditableField.tsx
  src/shared/utils/fetcher.ts
  src/widgets/change-password/ui/ChangePasswordForm.tsx
  src/widgets/delete-account/ui/DeleteAccountForm.tsx
  src/widgets/edit-profile/model/hooks.ts
  src/widgets/edit-profile/ui/EditProfileForm.tsx
  src/widgets/find-password/ui/FindPasswordForm.tsx
  src/widgets/find-username/ui/FindUsernameForm.tsx
  src/widgets/index.tsx
Labels: enhancement

#46 🔧 Update : Tour API -> 서버 API로 변경
  src/app/travel-info/page.tsx
  src/widgets/travel-info/components/AreaCode.tsx
  src/widgets/travel-info/components/AreaFilter.tsx
  src/widgets/travel-info/components/PlacesList.tsx
  src/widgets/travel-info/types/Place.ts
Labels: enhancement

#47 ✨ Feat: 북마크 목록 조회 페이지 추가
  src/app/my-scrap/page.tsx
  src/widgets/index.tsx
  src/widgets/my-info/ui/MyInfoForm.tsx
  src/widgets/my-scrap/api/useMyScraps.ts
  src/widgets/my-scrap/types/type.ts
  src/widgets/my-scrap/ui/ScrapItem.tsx
  src/widgets/my-scrap/ui/ScrapList.tsx
Labels: enhancement
